"""WebSocket event name constants mirroring frontend WS_EVENTS."""

EMERGENCY_INCOMING = "emergency:incoming"
EMERGENCY_ACCEPTED = "emergency:accepted"
AMBULANCE_LOCATION = "ambulance:location"
EMERGENCY_STATUS_UPDATE = "emergency:status"
AI_ANALYSIS_READY = "ai:analysis_ready"
NEW_PRESCRIPTION = "prescription:new"
NEW_REPORT = "report:new"
BED_STATUS_CHANGE = "hospital:bed_update"
APPOINTMENT_REMINDER = "appointment:reminder"
